sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: "mvn clean verify"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop
