sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache

install: true
script: ./mvnw clean install
script: 
  - "cd mutator/ && mvn clean test"
  - "mvn cobertura:cobertura"



